workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'maste'
      when: never
    - if: $CI_COMMIT_BRANCH == "maste"
      variables:
        TAG_NAME: api_server_runner
      when: always
    #- if: $CI_COMMIT_BRANCH == "dev"
 
stages:
- deploy
deploy:
  stage: deploy
  tags:
    - ${TAG_NAME}
  script:
  - docker compose down
  - docker rmi work_ozon_api-app
  - docker compose up -d
#